VERSION: GATv2_EnvGlobalNode_NoRespawn_test
runner: 'VGMRunner'
scene_data: 'gibson'
BASE_TASK_CONFIG_PATH: "configs/vistargetnav_gibson.yaml"
IL_TRAINER_NAME: "BC_trainer"
RL_TRAINER_NAME: "PPOTrainer_Memory_aux"
ENV_NAME: "SearchEnv"

SIMULATOR_GPU_ID: 2
TORCH_GPU_ID: 2

NUM_PROCESSES: 2
NUM_VAL_PROCESSES: 0

SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]

LOG_INTERVAL: 50
CHECKPOINT_INTERVAL: 200
VIS_INTERVAL: 200

OBS_TO_SAVE: ['global_memory', 'global_mask', 'global_A', 'global_time',
              'panoramic_rgb', 'panoramic_depth','goal_embedding', 'episode_info', 'target_goal',
              'step', 'have_been', 'target_dist_score']
POLICY: 'VGMPolicy'
WRAPPER: 'GraphWrapper'

GCN:
  TYPE: "GATv2"
  WITH_ENV_GLOBAL_NODE: True
  RANDOMINIT_ENV_GLOBAL_NODE: False
  RESPAWN_GLOBAL_NODE: False

REWARD_METHOD: 'progress'
USE_AUXILIARY_INFO: True

BC:
  max_epoch: 100 # defalt to 100
  batch_size: 16
  num_workers: 8

RL:
  SUCCESS_REWARD: 10.0
  SUCESS_MEASURE: 'SUCCESS'
  SLACK_REWARD: -0.001
  PPO:
    num_mini_batch: 2
    num_steps: 256
    rl_pretrained: True
    il_pretrained: False
    pretrained_weights: "data/new_checkpoints/GATv2_EnvGlobalNode_NoRespawn_ILRL_RL/ckpt.34.pth"
