VERSION: SMT
runner: 'SMTRunner'
scene_data: 'gibson'
BASE_TASK_CONFIG_PATH: "configs/SMT/vistargetnav_gibson.yaml"
IL_TRAINER_NAME: "BC_trainer"
RL_TRAINER_NAME: "PPOTrainer_Memory_aux"
ENV_NAME: "SearchEnv"

SIMULATOR_GPU_ID: 3
TORCH_GPU_ID: 3

NUM_PROCESSES: 4
NUM_VAL_PROCESSES: 0

# SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", 'COMPASS_SENSOR', 'GPSSensor'] # , 'SEMANTIC_SENSOR'

LOG_INTERVAL: 100
CHECKPOINT_INTERVAL: 200
VIS_INTERVAL: 200

OBS_TO_SAVE: ['global_memory', 'global_mask', 'global_A', 'global_time',
              'panoramic_rgb', 'panoramic_depth','compass','gps', 'cur_embedding', 'goal_embedding', 'episode_info', 'target_goal',
              'step', 'have_been', 'target_dist_score'] # ,'panoramic_semantic'
POLICY: 'SMTPolicy'
WRAPPER: 'StackedMemoryWrapper'

REWARD_METHOD: 'progress'
# USE_AUXILIARY_INFO: True

memory:
  memory_size: 260
  embedding_size: 256

transformer:
  hidden_dim: 128
  nheads: 8
  dim_feedforward: 128
BC:
  batch_size: 16
  num_workers: 8

RL:
  SUCCESS_REWARD: 10.0
  SUCESS_MEASURE: 'SUCCESS'
  SLACK_REWARD: -0.001
  PPO:
    num_mini_batch: 2
    num_steps: 256
    hidden_size: 512
    rl_pretrained: False
    il_pretrained: False
    pretrained_weights: "./data/new_checkpoints/vgm_RL/ckpt.15.pth"
