# for official settings, refer to https://github.com/joel99/objectnav/blob/main/configs/tasks/objectnav_mp3d.yaml
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
      MAX_SCENE_REPEAT_EPISODES: 100 #50
SIMULATOR:
  TYPE: 'Sim-0' # modified
  TURN_ANGLE: 10
  FORWARD_STEP_SIZE: 0.25
  ACTION_SPACE_CONFIG: "v0"
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    # HEIGHT: 1.25
    # RADIUS: 0.18
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    GPU_GPU: False
  RGB_SENSOR:
    WIDTH: 21
    HEIGHT: 64
    HFOV: 30
    POSITION: [0, 0.88, 0]
    #POSITION: [0, 1.25, 0]
  DEPTH_SENSOR:
    WIDTH: 21
    HEIGHT: 64
    HFOV: 30
    MIN_DEPTH: 0.
    MAX_DEPTH: 10.
    POSITION: [0, 0.88, 0]
    #POSITION: [0, 1.25, 0]
  SEMANTIC_SENSOR:
    WIDTH: 21
    HEIGHT: 64
    HFOV: 30
    POSITION: [0, 0.88, 0]
    # WIDTH: 64
    # HEIGHT: 256
    # HFOV: 30
    # POSITION: [0, 1.25, 0]
TASK:
  TYPE: Nav-v0 #MultiNav-v0
  POSSIBLE_ACTIONS: ["STOP","MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 1.0
  SENSORS: ['CUSTOM_VISTARGET_SENSOR',"PANORAMIC_SENSOR", "PANORAMIC_DEPTH_SENSOR"]
  GOAL_SENSOR_UUID: target_goal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL','TOP_DOWN_MAP', 'COLLISIONS']
  GOAL_INDEX: # modified
    TYPE: "Goal_Index" # See its definition in line 372 in custom_habitat_task.py. It should be the same as the class register name

  TOP_DOWN_MAP:
    DRAW_SOURCE: True
    DRAW_SHORTHEST_PATH: True
    DRAW_VIEW_POINTS: False
    DRAW_GOAL_POSITIONS: True
    DRAW_GOAL_AABBS: False
    FOG_OF_WAR:
      VISIBILITAY_DIST: 2.0
      FOV: 360
      DRAW: True
  
DATASET:
  TYPE: VisTargetNav-v1
  SPLIT: train
  #ON: 1_ON
  DATA_PATH: "data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
